[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
colosseum_programs = "4kX9b9hytCTrC6qikjVpnWYrvDK7NG97qCUDUTk9fMmn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
